#!/bin/bash

# Copyright 2016 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Common code used in the bash Jenkins job build phases

log_header(){
    echo
    echo "======================== $1 ================================="
    echo
}

jenkins_cli(){
  if [ -n "$BOP_JENKINS_CLI" ]; then
    $BOP_JENKINS_CLI -noCertificateCheck -s "$JENKINS_URL" "${@}"
    return $?
  else
    echo "BOP_JENKINS_CLI not set: cannot use Jenkins CLI"
    return 1
  fi
}

# Check if the supplied name is a valid component name, by checking if
# it has a valid dist-git entry.
component_sane(){
	echo "Checking if $1 is a valid parameter name"
	if [ -n "$BOP_DIST_GIT_URL" ]; then
    echo "Looking at $BOP_DIST_GIT_URL/$1"
    git ls-remote "$BOP_DIST_GIT_URL/$1" >/dev/null
    return $?
  else
    echo "BOP_DIST_GIT_URL not set: could not verify component sanity"
    return 1
  fi
}

set_current_build_description(){
  if [ -n "$JOB_NAME" ] && [ -n "$BUILD_NUMBER" ]
  then
    jenkins_cli set-build-description "$JOB_NAME" "$BUILD_NUMBER" "$1"
  else
    echo "Probably not running in a Jenkins build. Build description cannot be updated" >&2
  fi
}
