# Copyright 2016 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os.path
import glob


# pylint: disable=unused-argument
def configure(ctx):
    pass


def build(ctx):
    rebuild_jjb_tasks(ctx)


def rebuild_templated_jjb_task(ctx, name, yaml_file):
    ctx(rule="jenkins-jobs test -o jjb/ %s %s" % (ctx.path.abspath(), name),
        source="platform-defaults.yaml %s.yaml" % yaml_file, target="%s" % name)


def rebuild_jjb_tasks(ctx):
    templated_jobs = [("platform-component-setup-master", "platform-component-setup")]

    for job in templated_jobs:
        rebuild_templated_jjb_task(ctx, job[0], job[1])

