# Copyright 2016 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os.path
import glob


top = "."
out = "build"


def options(ctx):
    ctx.load("python")


def configure(ctx):
    ctx.find_program("jenkins-jobs")
    ctx.find_program("pep8")
    ctx.find_program("pylint")
    ctx.find_program("shellcheck")
    ctx.load("python")
    ctx.check_python_module("mock")
    ctx.check_python_module("koji")
    ctx.find_program("nosetests")

    ctx.recurse("scripts")
    ctx.recurse("jjb")


def build(ctx):
    python_static_analysis(ctx)
    ctx.recurse("scripts")
    ctx.recurse("jjb")
    ctx.recurse("platform_ci")


def pylint_file(ctx, python_file):
    ctx(rule="pylint --rcfile=%s/.pylint ${SRC} && touch ${TGT}" % ctx.srcnode.abspath(), source=python_file,
        target="%s.pylint" % python_file)


def pep8_file(ctx, python_file):
    ctx(rule="pep8 --ignore=E501 ${SRC} && touch ${TGT}", source=python_file, target="%s.pep8" % python_file)


def python_static_analysis(ctx):
    python_files = glob.glob(os.path.join(ctx.srcnode.abspath(), "*.py"))
    python_files.append("wscript")

    for python_file in python_files:
        pylint_file(ctx, python_file)
        pep8_file(ctx, python_file)
